"""add_student_academic_enrollment_table

Revision ID: 455830817e8c
Revises: c69b7a18161a
Create Date: 2025-12-19 00:09:31.788371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455830817e8c'
down_revision: Union[str, Sequence[str], None] = 'c69b7a18161a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_academic_enrollment',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='NULL for active enrollment'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('end_date IS NULL OR start_date <= end_date', name='ck_enrollment_dates'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Student academic enrollment - one active enrollment per student'
    )
    op.create_index('idx_student_enrollment_active', 'student_academic_enrollment', ['student_id'], unique=True, postgresql_where='end_date IS NULL')
    op.create_index(op.f('ix_student_academic_enrollment_academic_year_id'), 'student_academic_enrollment', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_academic_enrollment_student_id'), 'student_academic_enrollment', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_academic_enrollment_term_id'), 'student_academic_enrollment', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_academic_enrollment_term_id'), table_name='student_academic_enrollment')
    op.drop_index(op.f('ix_student_academic_enrollment_student_id'), table_name='student_academic_enrollment')
    op.drop_index(op.f('ix_student_academic_enrollment_academic_year_id'), table_name='student_academic_enrollment')
    op.drop_index('idx_student_enrollment_active', table_name='student_academic_enrollment', postgresql_where='end_date IS NULL')
    op.drop_table('student_academic_enrollment')
    # ### end Alembic commands ###
