"""Initial schema - all 25 tables

Revision ID: c69b7a18161a
Revises: 
Create Date: 2025-12-18 18:51:09.045216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69b7a18161a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ACTIVE | SUSPENDED'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED')", name='ck_school_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_school_name'),
    sa.UniqueConstraint('subdomain', name='uq_school_subdomain'),
    comment='School tenant - root entity for multi-tenancy'
    )
    op.create_table('academic_year',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.CheckConstraint('start_date < end_date', name='ck_academic_year_dates'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_year_school_name'),
    comment='Academic year with non-overlapping date ranges'
    )
    op.create_index(op.f('ix_academic_year_school_id'), 'academic_year', ['school_id'], unique=False)
    op.create_table('campus',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_campus_school_name'),
    comment='Campus belongs to a school with unique name per school'
    )
    op.create_index(op.f('ix_campus_school_id'), 'campus', ['school_id'], unique=False)
    op.create_table('class',
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Max number of students (1-100)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('capacity IS NULL OR (capacity > 0 AND capacity <= 100)', name='ck_class_capacity'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'academic_year_id', 'name', name='uq_class_campus_year_name'),
    comment='Class within campus and academic year'
    )
    op.create_index(op.f('ix_class_academic_year_id'), 'class', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_class_campus_id'), 'class', ['campus_id'], unique=False)
    op.create_table('student',
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='INACTIVE | ACTIVE | COMPLETED | TRANSFERRED_OUT'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.CheckConstraint("status IN ('INACTIVE', 'ACTIVE', 'COMPLETED', 'TRANSFERRED_OUT')", name='ck_student_status'),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Student records with tenant and campus isolation'
    )
    op.create_index('idx_student_school_campus', 'student', ['school_id', 'campus_id'], unique=False)
    op.create_index(op.f('ix_student_campus_id'), 'student', ['campus_id'], unique=False)
    op.create_index(op.f('ix_student_school_id'), 'student', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_status'), 'student', ['status'], unique=False)
    op.create_table('term',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('start_date < end_date', name='ck_term_dates'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Academic term - dates must be within academic year and not overlap'
    )
    op.create_index(op.f('ix_term_academic_year_id'), 'term', ['academic_year_id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Must start with +254 (Kenya format)'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='NULL until account setup complete (bcrypt hashed)'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='SUPER_ADMIN | SCHOOL_ADMIN | CAMPUS_ADMIN | TEACHER | PARENT'),
    sa.Column('campus_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ACTIVE | INACTIVE (PENDING_SETUP handled via password_hash NULL)'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.CheckConstraint("phone_number LIKE '+254%'", name='ck_user_phone_format'),
    sa.CheckConstraint("role IN ('SUPER_ADMIN', 'SCHOOL_ADMIN', 'CAMPUS_ADMIN', 'TEACHER', 'PARENT')", name='ck_user_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_user_status'),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'email', name='uq_user_school_email'),
    sa.UniqueConstraint('school_id', 'phone_number', name='uq_user_school_phone'),
    comment='User accounts with tenant isolation'
    )
    op.create_index('idx_user_school_role', 'user', ['school_id', 'role'], unique=False)
    op.create_index(op.f('ix_user_campus_id'), 'user', ['campus_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_school_id'), 'user', ['school_id'], unique=False)
    op.create_table('account_setup_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='Bcrypt hashed token (not plain text)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='NULL until used, then timestamp of use'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    comment='Account setup tokens - 7 day expiry, single-use'
    )
    op.create_index('idx_account_setup_token_expires', 'account_setup_token', ['expires_at'], unique=False)
    op.create_index('idx_account_setup_token_user', 'account_setup_token', ['user_id'], unique=False)
    op.create_index(op.f('ix_account_setup_token_expires_at'), 'account_setup_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_account_setup_token_user_id'), 'account_setup_token', ['user_id'], unique=False)
    op.create_table('announcement',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False, comment='PARENTS | TEACHERS | BOTH'),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.CheckConstraint("audience IN ('PARENTS', 'TEACHERS', 'BOTH')", name='ck_announcement_audience'),
    sa.CheckConstraint('title IS NOT NULL OR body IS NOT NULL', name='ck_announcement_content'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Event-based announcements with notifications'
    )
    op.create_index('idx_announcement_audience', 'announcement', ['school_id', 'audience'], unique=False)
    op.create_index('idx_announcement_created_at', 'announcement', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcement_created_by_user_id'), 'announcement', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_announcement_school_id'), 'announcement', ['school_id'], unique=False)
    op.create_table('fee',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Expected fee amount'),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount paid'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('expected_amount >= 0', name='ck_fee_expected_amount'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_fee_paid_amount'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term_id', name='uq_fee_student_term'),
    comment='Fee tracking - expected and paid amounts per student per term'
    )
    op.create_index('idx_fee_student', 'fee', ['student_id'], unique=False)
    op.create_index('idx_fee_term', 'fee', ['term_id'], unique=False)
    op.create_index(op.f('ix_fee_student_id'), 'fee', ['student_id'], unique=False)
    op.create_index(op.f('ix_fee_term_id'), 'fee', ['term_id'], unique=False)
    op.create_table('message_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='SMS | EMAIL | IN_APP'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='ACCOUNT_SETUP | PASSWORD_RESET | ANNOUNCEMENT | FEE_REMINDER | EMERGENCY'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='QUEUED | SENT | DELIVERED | FAILED'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.CheckConstraint("channel IN ('SMS', 'EMAIL', 'IN_APP')", name='ck_message_log_channel'),
    sa.CheckConstraint("status IS NULL OR status IN ('QUEUED', 'SENT', 'DELIVERED', 'FAILED')", name='ck_message_log_status'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Message log - audit trail of all sent messages'
    )
    op.create_index('idx_message_log_sent_at', 'message_log', ['sent_at'], unique=False)
    op.create_index('idx_message_log_type', 'message_log', ['message_type'], unique=False)
    op.create_index('idx_message_log_user', 'message_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_log_message_type'), 'message_log', ['message_type'], unique=False)
    op.create_index(op.f('ix_message_log_school_id'), 'message_log', ['school_id'], unique=False)
    op.create_index(op.f('ix_message_log_sent_at'), 'message_log', ['sent_at'], unique=False)
    op.create_index(op.f('ix_message_log_user_id'), 'message_log', ['user_id'], unique=False)
    op.create_table('notice_board_item',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False, comment='PARENTS | TEACHERS | BOTH'),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.CheckConstraint("audience IN ('PARENTS', 'TEACHERS', 'BOTH')", name='ck_notice_board_audience'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Persistent notice board items - no notifications'
    )
    op.create_index('idx_notice_board_item_audience', 'notice_board_item', ['school_id', 'audience'], unique=False)
    op.create_index(op.f('ix_notice_board_item_created_by_user_id'), 'notice_board_item', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_notice_board_item_school_id'), 'notice_board_item', ['school_id'], unique=False)
    op.create_table('parent',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False, comment='National ID or Passport number'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('school_id', sa.Uuid(), nullable=False, comment='School (tenant) this record belongs to'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Parent record - extends user with parent-specific data'
    )
    op.create_index(op.f('ix_parent_school_id'), 'parent', ['school_id'], unique=False)
    op.create_index(op.f('ix_parent_user_id'), 'parent', ['user_id'], unique=True)
    op.create_table('password_reset_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='Bcrypt hashed token (not plain text)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='NULL until used, then timestamp of use'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    comment='Password reset tokens - 1 hour expiry, single-use'
    )
    op.create_index('idx_password_reset_token_expires', 'password_reset_token', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_token_user', 'password_reset_token', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_expires_at'), 'password_reset_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_token_user_id'), 'password_reset_token', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='Bcrypt hashed token (not plain text)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='NULL if active, timestamp if revoked'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    comment='Refresh tokens - 24h or 30d expiry, can be revoked'
    )
    op.create_index('idx_refresh_token_expires', 'refresh_token', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_user', 'refresh_token', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_expires_at'), 'refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('student_class_history',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='NULL for active assignment'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Student class assignment history - one active assignment per student'
    )
    op.create_index('idx_student_class_active', 'student_class_history', ['student_id'], unique=True, postgresql_where='end_date IS NULL')
    op.create_index(op.f('ix_student_class_history_class_id'), 'student_class_history', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_class_history_student_id'), 'student_class_history', ['student_id'], unique=False)
    op.create_table('student_document',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('folder', sa.String(length=20), nullable=False, comment='PARENT | STUDENT | SCHOOL'),
    sa.Column('document_type', sa.String(length=200), nullable=False, comment='e.g., Birth Certificate, Parent ID, Report Card'),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False, comment='S3 URL or path'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes (max 10MB)'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type (e.g., application/pdf)'),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("folder IN ('PARENT', 'STUDENT', 'SCHOOL')", name='ck_student_document_folder'),
    sa.CheckConstraint('file_size > 0 AND file_size <= 10485760', name='ck_student_document_size'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Student document vault - files in S3'
    )
    op.create_index('idx_student_document_folder', 'student_document', ['student_id', 'folder'], unique=False)
    op.create_index(op.f('ix_student_document_student_id'), 'student_document', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_document_uploaded_by_user_id'), 'student_document', ['uploaded_by_user_id'], unique=False)
    op.create_table('student_term_comment',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False, comment='Overall term comment (1-2000 chars)'),
    sa.Column('entered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'term_id', 'id'),
    comment='Student term comment - one per student per term'
    )
    op.create_index('idx_student_term_comment_student', 'student_term_comment', ['student_id'], unique=False)
    op.create_index('idx_student_term_comment_term', 'student_term_comment', ['term_id'], unique=False)
    op.create_index(op.f('ix_student_term_comment_entered_by_user_id'), 'student_term_comment', ['entered_by_user_id'], unique=False)
    op.create_index(op.f('ix_student_term_comment_student_id'), 'student_term_comment', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_term_comment_term_id'), 'student_term_comment', ['term_id'], unique=False)
    op.create_table('subject',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True, comment='Subject code (unique within class if provided)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'code', name='uq_subject_class_code'),
    comment='Subject within a class'
    )
    op.create_index(op.f('ix_subject_class_id'), 'subject', ['class_id'], unique=False)
    op.create_table('announcement_attachment',
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Files attached to announcements'
    )
    op.create_index('idx_announcement_attachment_announcement', 'announcement_attachment', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_attachment_announcement_id'), 'announcement_attachment', ['announcement_id'], unique=False)
    op.create_table('notice_board_attachment',
    sa.Column('notice_board_item_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['notice_board_item_id'], ['notice_board_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Files attached to notice board items'
    )
    op.create_index('idx_notice_board_attachment_item', 'notice_board_attachment', ['notice_board_item_id'], unique=False)
    op.create_index(op.f('ix_notice_board_attachment_notice_board_item_id'), 'notice_board_attachment', ['notice_board_item_id'], unique=False)
    op.create_table('payment_history',
    sa.Column('fee_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Payment amount'),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True, comment='e.g., Cash, M-Pesa, Bank Transfer'),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='Transaction reference'),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('amount > 0', name='ck_payment_history_amount'),
    sa.ForeignKeyConstraint(['fee_id'], ['fee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Payment history - audit trail of all payments'
    )
    op.create_index('idx_payment_history_date', 'payment_history', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payment_history_fee_id'), 'payment_history', ['fee_id'], unique=False)
    op.create_index(op.f('ix_payment_history_payment_date'), 'payment_history', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payment_history_recorded_by_user_id'), 'payment_history', ['recorded_by_user_id'], unique=False)
    op.create_table('student_parent',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='FATHER | MOTHER | GUARDIAN'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("role IN ('FATHER', 'MOTHER', 'GUARDIAN')", name='ck_student_parent_role'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'role', name='uq_student_parent_role'),
    comment='Student-parent relationships with role constraints'
    )
    op.create_index('idx_student_parent_parent', 'student_parent', ['parent_id'], unique=False)
    op.create_index(op.f('ix_student_parent_parent_id'), 'student_parent', ['parent_id'], unique=False)
    op.create_index(op.f('ix_student_parent_student_id'), 'student_parent', ['student_id'], unique=False)
    op.create_table('student_performance',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True, comment='Grade (e.g., A, A+, B, 85%)'),
    sa.Column('subject_comment', sa.Text(), nullable=True, comment='Subject-level comment (max 1000 chars)'),
    sa.Column('entered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'subject_id', 'term_id', 'id'),
    comment='Student performance - one grade per student per subject per term'
    )
    op.create_index('idx_student_performance_student', 'student_performance', ['student_id'], unique=False)
    op.create_index('idx_student_performance_subject', 'student_performance', ['subject_id'], unique=False)
    op.create_index('idx_student_performance_term', 'student_performance', ['term_id'], unique=False)
    op.create_index(op.f('ix_student_performance_entered_by_user_id'), 'student_performance', ['entered_by_user_id'], unique=False)
    op.create_index(op.f('ix_student_performance_student_id'), 'student_performance', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_performance_subject_id'), 'student_performance', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_performance_term_id'), 'student_performance', ['term_id'], unique=False)
    op.create_table('teacher_class_assignment',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True, comment='NULL if teaching all subjects in class'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='NULL for active assignment'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Teacher assignments to classes/subjects - time-bound'
    )
    op.create_index('idx_teacher_class_active', 'teacher_class_assignment', ['teacher_id', 'class_id'], unique=False, postgresql_where='end_date IS NULL')
    op.create_index(op.f('ix_teacher_class_assignment_class_id'), 'teacher_class_assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_assignment_subject_id'), 'teacher_class_assignment', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_assignment_teacher_id'), 'teacher_class_assignment', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_class_assignment_teacher_id'), table_name='teacher_class_assignment')
    op.drop_index(op.f('ix_teacher_class_assignment_subject_id'), table_name='teacher_class_assignment')
    op.drop_index(op.f('ix_teacher_class_assignment_class_id'), table_name='teacher_class_assignment')
    op.drop_index('idx_teacher_class_active', table_name='teacher_class_assignment', postgresql_where='end_date IS NULL')
    op.drop_table('teacher_class_assignment')
    op.drop_index(op.f('ix_student_performance_term_id'), table_name='student_performance')
    op.drop_index(op.f('ix_student_performance_subject_id'), table_name='student_performance')
    op.drop_index(op.f('ix_student_performance_student_id'), table_name='student_performance')
    op.drop_index(op.f('ix_student_performance_entered_by_user_id'), table_name='student_performance')
    op.drop_index('idx_student_performance_term', table_name='student_performance')
    op.drop_index('idx_student_performance_subject', table_name='student_performance')
    op.drop_index('idx_student_performance_student', table_name='student_performance')
    op.drop_table('student_performance')
    op.drop_index(op.f('ix_student_parent_student_id'), table_name='student_parent')
    op.drop_index(op.f('ix_student_parent_parent_id'), table_name='student_parent')
    op.drop_index('idx_student_parent_parent', table_name='student_parent')
    op.drop_table('student_parent')
    op.drop_index(op.f('ix_payment_history_recorded_by_user_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_payment_date'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_fee_id'), table_name='payment_history')
    op.drop_index('idx_payment_history_date', table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_notice_board_attachment_notice_board_item_id'), table_name='notice_board_attachment')
    op.drop_index('idx_notice_board_attachment_item', table_name='notice_board_attachment')
    op.drop_table('notice_board_attachment')
    op.drop_index(op.f('ix_announcement_attachment_announcement_id'), table_name='announcement_attachment')
    op.drop_index('idx_announcement_attachment_announcement', table_name='announcement_attachment')
    op.drop_table('announcement_attachment')
    op.drop_index(op.f('ix_subject_class_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_student_term_comment_term_id'), table_name='student_term_comment')
    op.drop_index(op.f('ix_student_term_comment_student_id'), table_name='student_term_comment')
    op.drop_index(op.f('ix_student_term_comment_entered_by_user_id'), table_name='student_term_comment')
    op.drop_index('idx_student_term_comment_term', table_name='student_term_comment')
    op.drop_index('idx_student_term_comment_student', table_name='student_term_comment')
    op.drop_table('student_term_comment')
    op.drop_index(op.f('ix_student_document_uploaded_by_user_id'), table_name='student_document')
    op.drop_index(op.f('ix_student_document_student_id'), table_name='student_document')
    op.drop_index('idx_student_document_folder', table_name='student_document')
    op.drop_table('student_document')
    op.drop_index(op.f('ix_student_class_history_student_id'), table_name='student_class_history')
    op.drop_index(op.f('ix_student_class_history_class_id'), table_name='student_class_history')
    op.drop_index('idx_student_class_active', table_name='student_class_history', postgresql_where='end_date IS NULL')
    op.drop_table('student_class_history')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_expires_at'), table_name='refresh_token')
    op.drop_index('idx_refresh_token_user', table_name='refresh_token')
    op.drop_index('idx_refresh_token_expires', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_password_reset_token_user_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_expires_at'), table_name='password_reset_token')
    op.drop_index('idx_password_reset_token_user', table_name='password_reset_token')
    op.drop_index('idx_password_reset_token_expires', table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_parent_user_id'), table_name='parent')
    op.drop_index(op.f('ix_parent_school_id'), table_name='parent')
    op.drop_table('parent')
    op.drop_index(op.f('ix_notice_board_item_school_id'), table_name='notice_board_item')
    op.drop_index(op.f('ix_notice_board_item_created_by_user_id'), table_name='notice_board_item')
    op.drop_index('idx_notice_board_item_audience', table_name='notice_board_item')
    op.drop_table('notice_board_item')
    op.drop_index(op.f('ix_message_log_user_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_sent_at'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_school_id'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_message_type'), table_name='message_log')
    op.drop_index('idx_message_log_user', table_name='message_log')
    op.drop_index('idx_message_log_type', table_name='message_log')
    op.drop_index('idx_message_log_sent_at', table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_fee_term_id'), table_name='fee')
    op.drop_index(op.f('ix_fee_student_id'), table_name='fee')
    op.drop_index('idx_fee_term', table_name='fee')
    op.drop_index('idx_fee_student', table_name='fee')
    op.drop_table('fee')
    op.drop_index(op.f('ix_announcement_school_id'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_created_by_user_id'), table_name='announcement')
    op.drop_index('idx_announcement_created_at', table_name='announcement')
    op.drop_index('idx_announcement_audience', table_name='announcement')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_account_setup_token_user_id'), table_name='account_setup_token')
    op.drop_index(op.f('ix_account_setup_token_expires_at'), table_name='account_setup_token')
    op.drop_index('idx_account_setup_token_user', table_name='account_setup_token')
    op.drop_index('idx_account_setup_token_expires', table_name='account_setup_token')
    op.drop_table('account_setup_token')
    op.drop_index(op.f('ix_user_school_id'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_campus_id'), table_name='user')
    op.drop_index('idx_user_school_role', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_term_academic_year_id'), table_name='term')
    op.drop_table('term')
    op.drop_index(op.f('ix_student_status'), table_name='student')
    op.drop_index(op.f('ix_student_school_id'), table_name='student')
    op.drop_index(op.f('ix_student_campus_id'), table_name='student')
    op.drop_index('idx_student_school_campus', table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_class_campus_id'), table_name='class')
    op.drop_index(op.f('ix_class_academic_year_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_campus_school_id'), table_name='campus')
    op.drop_table('campus')
    op.drop_index(op.f('ix_academic_year_school_id'), table_name='academic_year')
    op.drop_table('academic_year')
    op.drop_table('school')
    # ### end Alembic commands ###
